version: '3'
services:
  chrome:
    image: selenium/node-chrome:112.0-chromedriver-112.0

  tests:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    build: .
    depends_on:
      - chrome
    volumes:
      - "./tests:/var/www/tests"
  allure:
    image: frankescobar/allure-docker-service
    ports:
      - "4040:4040"
    volumes:
      - allure-results:/app/allure-results
      - allure-report:/app/allure-report

volumes:
  allure-results:
  allure-report: